source "https://rubygems.org"

ruby '1.9.3', :engine => 'jruby', :engine_version => '1.7.4'

platforms :jruby do
  gem "warbler", "~> 1.3.8"

  group :production do
    # Any jruby-specific gems you want in your JAR
  end
end

group :production do
  # Any general gems you want in your JAR
end
